config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  Rails.application.config.default_url_options = { host: 'localhost', port: 3000 }

  resources :password_resets, only: [:new, :create, :edit, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  root 'home#index'

  # Кабинет администратора
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    resources :teachers, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  get '/admin/subjects/:id', to: 'admin/subjects#destroy', as: 'destroy_admin_subject'
  get '/admin/students/:id', to: 'admin/students#destroy', as: 'destroy_admin_student'



  # Кабинет учителя
  namespace :teacher do
    root to: 'dashboard#index', as: 'dashboard'
    resources :grades, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
    post '/grades', to: 'grades#create'
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  acts_as_paranoid
  has_many :assignments, dependent: :destroy
  has_many :teachers, through: :assignments

  after_destroy_commit -> { broadcast_remove_to self }
  after_create_commit lambda {
                        broadcast_after_to 'subjects', target: 'tr_table', partial: 'components/subject',
                                                       locals: { subject: self }
                      }
  after_update_commit -> { broadcast_replace_to self, partial: 'components/subject', locals: { subject: self } }

  validates :name, presence: true, uniqueness: true
  scope :by_subject_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
end

app/controllers/admin/subjects_controller.rb
module Admin
  class SubjectsController < ApplicationController
    has_scope :by_subject_name, as: :subject_name, only: :index
    has_scope :by_teacher_name, as: :teacher_name, only: :index

    def index
      @subjects = apply_scopes(Subject).page(params[:page]).per(5)
    end

    def new
      @subject = Subject.new
      @teachers = Users::Teacher.all
    end

    def edit
      @subject = Subject.find(params[:id])
      @teachers = Users::Teacher.all
    end

    def create
      @subject = Subject.new(subject_params)
      @teachers = Users::Teacher.all

      if @subject.save
        redirect_to admin_dashboard_path(table: 'subjects')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      @subject = Subject.find(params[:id])
      @teachers = Users::Teacher.all

      if @subject.update(subject_params)
        redirect_to admin_dashboard_path(table: 'subjects')
      else
        render :edit
      end
    end

    def destroy
      @subject = Subject.find(params[:id])
      @subject.destroy
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.destroy(@subject) }
        format.html { redirect_to admin_dashboard_path(table: 'subjects') }
      end
    end

    private

    def subject_params
      params.require(:subject).permit(:name, teacher_ids: [])
    end
  end
end

app/controllers/teacher/subjects_controller.rb
module Teacher
  class SubjectsController < ApplicationController
    def index
      @subjects = Subject.all
      @grade = Grade.new
      @selected_student = Student.find_by(id: params[:student_id]) if params[:student_id].present?
      @selected_subject = Subject.find_by(id: params[:subject_id]) if params[:subject_id].present?
      load_grades_for_selected_subject if @selected_subject && @selected_student
    end

    private

    def load_grades_for_selected_subject
      @grades = @selected_subject.grades.where(student_id: @selected_student.id)
                                 .order(:date)
                                 .page(params[:page])
                                 .per(10)
    end
  end
end

app/views/admin/subjects/destroy.turbo_stream.slim
- turbo_stream.destroy "subject_#{@subject_id}"

app/views/admin/subjects/edit.html.slim
.px-4.sm:px-6.lg:px-8
  h1.text-2xl.font-bold.mb-12.my-12 Редактировать предмет
  = form_with(model: @subject, url: admin_subject_path(@subject), method: :patch, class: "space-y-4") do |form|
    .space-y-2
      = form.label :name, "Название предмета", class: "block font-medium text-gray-700 text-base"
      = form.text_field :name, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .mt-4
      .button-group
        = form.label :teacher_ids, "Выберите учителей", class: "block font-medium text-gray-700 text-base", data: { toggle: "dropdown" }
        ul.dropdown-menu
          - @teachers.each do |teacher|
            li
              a.small
                = form.check_box :teacher_ids, { multiple: true }, teacher.id, nil
                = teacher.name
    .flex.justify-end
      = render partial: 'components/form_button', locals: { form: form, name: 'Обновить данные о предмете' }
= link_to 'Назад', admin_dashboard_path(table: 'subjects'), class: "block mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-md shadow hover:bg-gray-300 focus:outline-none focus:bg-gray-300"

app/views/admin/subjects/new.html.slim
= form_with(model: @subject, url: admin_subjects_path, method: :post, id: 'new_subject_form') do |form|
  - if @subject.errors.any?
    #error_explanation.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.relative
      h2.font-bold = pluralize(@subject.errors.count, "error")
      ul.mt-3.list-disc.list-inside
        - @subject.errors.full_messages.each do |message|
          li = message

  .mt-4.px-4
    = form.label :name, "Название предмета", class: "block text-gray-700 text-base font-bold mb-2"
    = form.text_field :name, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"

  .mt-4.px-4
    .button-group
      = form.label :teacher_ids, "Выберите учителей", class: "block text-gray-700 text-base font-bold mb-2", data: { toggle: "dropdown" }
      ul.dropdown-menu
        - @teachers.each do |teacher|
          li
            label.small
              = form.check_box :teacher_ids, { multiple: true }, teacher.id, nil
              = teacher.name

  .mt-4
    = render partial: 'components/form_button', locals: { form: form, name: 'Создать предмет' }

= link_to 'Назад', admin_dashboard_path(table: 'subjects'), class: "block mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-md shadow hover:bg-gray-300 focus:outline-none focus:bg-gray-300"