config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  Rails.application.config.default_url_options = { host: 'localhost', port: 3000 }

  resources :password_resets, only: [:new, :create, :edit, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  root 'home#index'

  # Кабинет администратора
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    resources :teachers, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  get '/admin/subjects/:id', to: 'admin/subjects#destroy', as: 'destroy_admin_subject'
  get '/admin/students/:id', to: 'admin/students#destroy', as: 'destroy_admin_student'



  # Кабинет учителя
  namespace :teacher do
    root to: 'dashboard#index', as: 'dashboard'
    resources :grades, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
    post '/grades', to: 'grades#create'
  end
end

app/models/student.rb
class Student < ApplicationRecord
  acts_as_paranoid
  has_many :grades, dependent: :destroy
  has_many :subjects, through: :grades

  after_destroy_commit -> { broadcast_remove_to self }
  after_create_commit lambda {
                        broadcast_after_to 'students', target: 'tr_table', partial: 'components/student',
                                                       locals: { student: self }
                      }
  after_update_commit -> { broadcast_replace_to self, partial: 'components/student', locals: { student: self } }

  scope :by_student_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
  scope :by_student_email, ->(email) { where('email ILIKE ?', "%#{email}%") }
  scope :by_student_phone_number, ->(phone_number) { where('phone_number ILIKE ?', "%#{phone_number}%") }

  def average_grade(subject)
    grades.where(subject: subject).average(:value)
  end
end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < ApplicationController
    has_scope :by_student_name, as: :student_name, only: :index
    has_scope :by_student_email, as: :student_email, only: :index
    has_scope :by_student_phone_number, as: :student_phone, only: :index

    def index
      @students = apply_scopes(Student).page(params[:page]).per(5)
    end

    def new
      @student = Student.new
    end

    def edit
      @student = Student.find(params[:id])
    end

    def create
      @student = Student.new(student_params)
      if @student.save
        redirect_to admin_dashboard_path(table: 'students')
      else
        render :new
      end
    end

    def update
      @student = Student.find(params[:id])
      if @student.update(student_params)
        redirect_to admin_dashboard_path(table: 'students')
      else
        render :edit
      end
    end

    def destroy
      @student = Student.find(params[:id])
      @student.destroy
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.destroy(@subject) }
        format.html { redirect_to admin_dashboard_path(table: 'students') }
      end
    end

    private

    def student_params
      params.require(:student).permit(:name, :email, :phone_number)
    end
  end
end

app/controllers/teacher/students_controller.rb
module Teacher
  class StudentsController < ApplicationController
    has_scope :by_student_name, as: :student_name, only: :index
    has_scope :by_student_email, as: :student_email, only: :index
    has_scope :by_student_phone_number, as: :student_phone, only: :index

    def index
      @students = apply_scopes(Student).page(params[:page]).per(5)
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/students/destroy.turbo_stream.slim
- turbo_stream.destroy "student_#{@student_id}"

app/views/admin/students/edit.html.slim
.px-4.sm:px-6.lg:px-8
  h1.text-2xl.font-bold.mb-12.my-12 Редактировать ученика
  = form_with(model: @student, url: admin_student_path(@student), method: :patch, class: "space-y-4") do |form|
    .space-y-2
      = form.label :name, "Имя ученика", class: "block font-medium text-gray-700"
      = form.text_field :name, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .space-y-2
      = form.label :phone_number, "Номер телефона ученика", class: "block font-medium text-gray-700"
      = form.text_field :phone_number, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .space-y-2
      = form.label :email, "Email ученика", class: "block font-medium text-gray-700"
      = form.email_field :email, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .flex.justify-end
      = render partial: 'components/form_button', locals: { form: form, name: 'Обновить данные об ученике' }
  = link_to 'Назад', admin_dashboard_path(table: 'students'), class: "block mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-md shadow hover:bg-gray-300 focus:outline-none focus:bg-gray-300"

app/views/admin/students/new.html.slim
.px-4.sm:px-6.lg:px-8
  h1.text-2xl.font-bold.mb-12.my-12 Новый ученик
  = form_with(model: @student, url: admin_students_path, method: :post) do |form|
    .mb-4.mx-4
      = form.label :name, "Имя ученика", class: "block text-gray-700 text-base font-bold mb-2"
      = form.text_field :name, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .mb-4.mx-4
      = form.label :phone_number, "Номер телефона ученика", class: "block text-gray-700 text-base font-bold mb-2"
      = form.text_field :phone_number, id: "student_phone_number", class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    .mb-4.mx-4
      = form.label :email,"Email ученика", class: "block text-gray-700 text-base font-bold mb-2"
      = form.text_field :email, class: "form-input w-full rounded-md border border-gray-600 shadow-lg focus:outline-none focus:border-violet-500 px-2"
    div
      = render partial: 'components/form_button', locals: { form: form, name: 'Добавить ученика' }
  = link_to 'Назад', admin_dashboard_path(table: 'students'), class: "block mt-4 py-2 px-4 bg-gray-200 text-gray-800 rounded-md shadow hover:bg-gray-300 focus:outline-none focus:bg-gray-300"