config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  Rails.application.config.default_url_options = { host: 'localhost', port: 3000 }

  resources :password_resets, only: [:new, :create, :edit, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  root 'home#index'

  # Кабинет администратора
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    resources :teachers, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  get '/admin/subjects/:id', to: 'admin/subjects#destroy', as: 'destroy_admin_subject'
  get '/admin/students/:id', to: 'admin/students#destroy', as: 'destroy_admin_student'



  # Кабинет учителя
  namespace :teacher do
    root to: 'dashboard#index', as: 'dashboard'
    resources :grades, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
    post '/grades', to: 'grades#create'
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_action :set_current_table
    before_action :authorize_admin

    def index
      case @current_table
      when 'subjects'
        fetch_subjects
      when 'teachers'
        fetch_teachers
      when 'students'
        fetch_students
      end
    end

    private

    def set_current_table
      @current_table = params[:table] || 'subjects'
    end

    def authorize_admin
      authorize! :access, :admin_dashboard
    end

    def fetch_students
      @students = Student.all
      @students = @students.by_student_name(params[:student_name]) if params[:student_name].present?
      @students = @students.by_student_email(params[:student_email]) if params[:student_email].present?
      @students = @students.by_student_phone_number(params[:student_phone]) if params[:student_phone].present?
      @students = @students.page(params[:page]).per(10)
    end

    def fetch_subjects
      @subjects = Subject.all
      @subjects = @subjects.by_subject_name(params[:subject_name]) if params[:subject_name].present?
      @subjects = @subjects.by_teacher_name(params[:teacher_name]) if params[:teacher_name].present?
      @subjects = @subjects.page(params[:page]).per(10)
    end

    def fetch_teachers
      @teachers = Users::Teacher.all
      @teachers = @teachers.by_teacher_name(params[:teacher_name]) if params[:teacher_name].present?
      @teachers = @teachers.by_teacher_email(params[:teacher_email]) if params[:teacher_email].present?
      @teachers = @teachers.by_teacher_phone_number(params[:teacher_phone]) if params[:teacher_phone].present?
      @teachers = @teachers.page(params[:page]).per(10)
    end
  end
end

app/controllers/teacher/dashboard_controller.rb
module Teacher
  class DashboardController < ApplicationController
    before_action :set_current_table
    before_action :authorize_teacher
    before_action :fetch_subjects, only: [:index]

    has_scope :by_student_name, as: :student_name, only: :index
    has_scope :by_student_email, as: :student_email, only: :index
    has_scope :by_student_phone_number, as: :student_phone, only: :index

    def index
      case @current_table
      when 'teacher_students'
        @students = Student.all
        @students = apply_scopes(@students).page(params[:page]).per(5)
      when 'student_grades'
        @students = Student.all
        fetch_student_grades
      end
    end

    private

    def set_current_table
      @current_table = params[:table] || 'teacher_students'
    end

    def authorize_teacher
      authorize! :access, :teacher_dashboard
    end

    def fetch_student_grades
      @selected_student = Student.find_by(id: params[:student_id]) if params[:student_id].present?
      @selected_subject = Subject.find_by(id: params[:subject_id]) if params[:subject_id].present?
    end

    def fetch_subjects
      @subjects = Subject.all
    end
  end
end

app/views/admin/dashboard/_filter_students.html.slim
= form_with url: admin_dashboard_path(table: @current_table), method: :get, class: "mb-4" do |form|
  = form.hidden_field :table, value: @current_table
  .flex.space-x-4
    .flex
      = form.label :student_name, "Имя ученика", class: "p-2"
      = form.text_field :student_name,  class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :student_email, "Email ученика", class: "p-2"
      = form.text_field :student_email,  class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :student_phone, "Телефон ученика", class: "p-2"
      = form.text_field :student_phone,  class: "border border-gray-300 p-2 rounded"
    .flex.items-end
      = form.button "Фильтр", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm \
      font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline \
      focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/admin/dashboard/_filter_subjects.html.slim
= form_with url: admin_dashboard_path(table: @current_table), method: :get, class: "mb-4" do |form|
  = form.hidden_field :table, value: @current_table
  .flex.space-x-4
    .flex
      = form.label :subject_name, "Название предмета", class: "p-2"
      = form.text_field :subject_name, class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :teacher_name, "Имя учителя", class: "p-2"
      = form.text_field :teacher_name, class: "border border-gray-300 p-2 rounded"
    .flex.items-end
      = form.button "Фильтр", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm \
                              font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline \
                              focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/admin/dashboard/_filter_teachers.html.slim
= form_with url: admin_dashboard_path(table: @current_table), method: :get,  class: "mb-4" do |form|
  = form.hidden_field :table, value: @current_table
  .flex.space-x-4
    .flex
      = form.label :teacher_name, "Имя учителя", class: "p-2"
      = form.text_field :teacher_name,  class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :teacher_email, "Email учителя", class: "p-2"
      = form.text_field :teacher_email,  class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :teacher_phone, "Номер телефон учителя", class: "p-2"
      = form.text_field :teacher_phone,  class: "border border-gray-300 p-2 rounded"
    .flex.items-end
      = form.button "Фильтр", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 \
                                      text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 \
                                      focus-visible:outline focus-visible:outline-2 \
                                      focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/admin/dashboard/index.html.slim
nav.bg-violet-100.mb-4
  .mx-auto.max-w-7xl.px-2.sm:px-6.lg:px-8
    .relative.flex.h-16.items-center.justify-between
      .flex-1
        - if current_user
          = link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete }, class: "max-w-md mx-4 px-6 py-3 my-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
      .text-center.w-full
        h1.text-2xl.font-bold.mb-4 Кабинет Администратора
      .flex-2
        - if @current_user
          span.mr-4.font-bold Здравствуйте, #{@current_user.name}!

.container.mx-auto
  - if @current_table == 'subjects'
    .mb-4
      h2.text-xl.font-bold.mb-4 Список предметов
      = turbo_frame_tag "filter"
        = render partial: "filter_subjects", locals: { current_table: @current_table }
        = render partial: 'components/subjects_table', locals: { subjects: @subjects }
    .mt-8
      = render partial: 'components/button', locals: { url: new_admin_subject_path, name: 'Добавить предмет' }, class: "my-12"
    .mt-8
      = paginate @subjects, params: { subject_name: params[:subject_name], teacher_name: params[:teacher_name] }

  - elsif @current_table == 'teachers'
    .mb-4
      h2.text-xl.font-bold.mb-4 Список учителей
      = turbo_frame_tag "filter"
        = render partial: "filter_teachers", locals: { current_table: @current_table }
        = render partial: 'components/teachers_table', locals: { teachers: @teachers }
    .mt-8
      = paginate @teachers, params: { teacher_name: params[:teacher_name], teacher_email: params[:teacher_email], teacher_phone: params[:teacher_phone] }

  - elsif @current_table == 'students'
    .mb-4
      h2.text-xl.font-bold.mb-4 Список учеников
      = turbo_frame_tag "filter"
        = render partial: "filter_students", locals: { current_table: @current_table }
        = render partial: 'components/students_table', locals: { students: @students }
    .mt-8
      = render partial: 'components/button', locals: { url: new_admin_student_path, name: 'Добавить ученика' }, class: "my-12"
    .mt-8
      = paginate @students, params: { student_name: params[:student_name], student_email: params[:student_email], student_phone: params[:student_phone] }

  .flex.justify-center.mb-2
    = link_to 'Предметы', admin_dashboard_path(table: 'subjects'), class: 'mx-2 px-4 py-2 bg-indigo-600 text-white rounded'
    = link_to 'Учителя', admin_dashboard_path(table: 'teachers'), class: 'mx-2 px-4 py-2 bg-pink-500 text-white rounded'
    = link_to 'Студенты', admin_dashboard_path(table: 'students'), class: 'mx-2 px-4 py-2 bg-purple-600 text-white rounded'