config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  Rails.application.config.default_url_options = { host: 'localhost', port: 3000 }

  resources :password_resets, only: [:new, :create, :edit, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  root 'home#index'

  # Кабинет администратора
  namespace :admin do
    root to: 'dashboard#index', as: 'dashboard'
    resources :teachers, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  get '/admin/subjects/:id', to: 'admin/subjects#destroy', as: 'destroy_admin_subject'
  get '/admin/students/:id', to: 'admin/students#destroy', as: 'destroy_admin_student'



  # Кабинет учителя
  namespace :teacher do
    root to: 'dashboard#index', as: 'dashboard'
    resources :grades, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :students, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :subjects, only: [:index, :new, :create, :edit, :update, :destroy]
    post '/grades', to: 'grades#create'
  end
end

app/models/users/teacher.rb
module Users
  class Teacher < User
    has_many :assignments, dependent: :destroy
    has_many :subjects, through: :assignments

    scope :by_teacher_name, ->(name) { where('name ILIKE ?', "%#{name}%") }
    scope :by_teacher_email, ->(email) { where('email ILIKE ?', "%#{email}%") }
    scope :by_teacher_phone_number, ->(phone_number) { where('phone_number ILIKE ?', "%#{phone_number}%") }

    def teacher?
      true
    end

    def admin?
      false
    end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_action :set_current_table
    before_action :authorize_admin

    def index
      case @current_table
      when 'subjects'
        fetch_subjects
      when 'teachers'
        fetch_teachers
      when 'students'
        fetch_students
      end
    end

    private

    def set_current_table
      @current_table = params[:table] || 'subjects'
    end

    def authorize_admin
      authorize! :access, :admin_dashboard
    end

    def fetch_students
      @students = Student.all
      @students = @students.by_student_name(params[:student_name]) if params[:student_name].present?
      @students = @students.by_student_email(params[:student_email]) if params[:student_email].present?
      @students = @students.by_student_phone_number(params[:student_phone]) if params[:student_phone].present?
      @students = @students.page(params[:page]).per(10)
    end

    def fetch_subjects
      @subjects = Subject.all
      @subjects = @subjects.by_subject_name(params[:subject_name]) if params[:subject_name].present?
      @subjects = @subjects.by_teacher_name(params[:teacher_name]) if params[:teacher_name].present?
      @subjects = @subjects.page(params[:page]).per(10)
    end

    def fetch_teachers
      @teachers = Users::Teacher.all
      @teachers = @teachers.by_teacher_name(params[:teacher_name]) if params[:teacher_name].present?
      @teachers = @teachers.by_teacher_email(params[:teacher_email]) if params[:teacher_email].present?
      @teachers = @teachers.by_teacher_phone_number(params[:teacher_phone]) if params[:teacher_phone].present?
      @teachers = @teachers.page(params[:page]).per(10)
    end
  end
end

app/controllers/admin/teachers_controller.rb
module Admin
  class TeachersController < ApplicationController
    has_scope :by_teacher_name, as: :teacher_name, only: :index
    has_scope :by_teacher_email, as: :teacher_email, only: :index
    has_scope :by_teacher_phone_number, as: :teacher_phone, only: :index

    def index
      @teachers = apply_scopes(Users::Teacher).page(params[:page]).per(5)
    end

    private

    def teacher_params
      params.require(:users_teacher).permit(:name, :email)
    end
  end
end

app/controllers/teacher/dashboard_controller.rb
module Teacher
  class DashboardController < ApplicationController
    before_action :set_current_table
    before_action :authorize_teacher
    before_action :fetch_subjects, only: [:index]

    has_scope :by_student_name, as: :student_name, only: :index
    has_scope :by_student_email, as: :student_email, only: :index
    has_scope :by_student_phone_number, as: :student_phone, only: :index

    def index
      case @current_table
      when 'teacher_students'
        @students = Student.all
        @students = apply_scopes(@students).page(params[:page]).per(5)
      when 'student_grades'
        @students = Student.all
        fetch_student_grades
      end
    end

    private

    def set_current_table
      @current_table = params[:table] || 'teacher_students'
    end

    def authorize_teacher
      authorize! :access, :teacher_dashboard
    end

    def fetch_student_grades
      @selected_student = Student.find_by(id: params[:student_id]) if params[:student_id].present?
      @selected_subject = Subject.find_by(id: params[:subject_id]) if params[:subject_id].present?
    end

    def fetch_subjects
      @subjects = Subject.all
    end
  end
end

app/controllers/teacher/grades_controller.rb
module Teacher
  class GradesController < ApplicationController
    before_action :load_grades_for_selected_subject, only: [:index]

    def index
      @grade = Grade.new
    end

    def create
      @grade = Grade.new(grade_params)
      if @grade.save
        redirect_to teacher_dashboard_path(table: 'student_grades')
      else
        render :index
      end
    end

    private

    def load_grades_for_selected_subject
      @selected_subject = Subject.find_by(id: params[:grade][:subject_id])
      @selected_student = Student.find_by(id: params[:grade][:student_id])
      return unless @selected_subject && @selected_student

      @grades = @selected_subject.grades.where(student_id: @selected_student.id)
                                 .order(:date)
                                 .page(params[:page])
                                 .per(10)
    end

    def grade_params
      params.require(:grade).permit(:student_id, :subject_id, :date, :value)
    end

    def set_selected_subject_session
      session[:selected_subject_id] = @grade.subject_id
    end
  end
end

app/controllers/teacher/students_controller.rb
module Teacher
  class StudentsController < ApplicationController
    has_scope :by_student_name, as: :student_name, only: :index
    has_scope :by_student_email, as: :student_email, only: :index
    has_scope :by_student_phone_number, as: :student_phone, only: :index

    def index
      @students = apply_scopes(Student).page(params[:page]).per(5)
    end
  end
end

app/controllers/teacher/subjects_controller.rb
module Teacher
  class SubjectsController < ApplicationController
    def index
      @subjects = Subject.all
      @grade = Grade.new
      @selected_student = Student.find_by(id: params[:student_id]) if params[:student_id].present?
      @selected_subject = Subject.find_by(id: params[:subject_id]) if params[:subject_id].present?
      load_grades_for_selected_subject if @selected_subject && @selected_student
    end

    private

    def load_grades_for_selected_subject
      @grades = @selected_subject.grades.where(student_id: @selected_student.id)
                                 .order(:date)
                                 .page(params[:page])
                                 .per(10)
    end
  end
end

app/views/teacher/dashboard/_filter_students.html.slim
= form_with url: teacher_dashboard_path(table: @current_table), method: :get, local: true, class: "mb-4" do |form|
  = form.hidden_field :table, value: @current_table
  .flex.space-x-4
    .flex
      = form.label :student_name, "Имя ученика", class: "p-2"
      = form.text_field :student_name, class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :student_email, "Email ученика", class: "p-2"
      = form.text_field :student_email, class: "border border-gray-300 p-2 rounded"
    .flex
      = form.label :student_phone, "Телефон ученика", class: "p-2"
      = form.text_field :student_phone, class: "border border-gray-300 p-2 rounded"
    .flex.items-end
      = form.button "Фильтр", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/teacher/dashboard/index.html.slim
nav.bg-violet-100.mb-4
  .mx-auto.max-w-7xl.px-2.sm:px-6.lg:px-8
    .relative.flex.h-16.items-center.justify-between
      .flex-1
        - if current_user
          = link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete }, class: "max-w-md mx-4 px-6 py-3 my-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
      .text-center.w-full
        h1.text-2xl.font-bold.mb-4 Кабинет Учителя
      .flex-2
        - if @current_user
          span.mr-4.font-bold Здравствуйте, #{@current_user.name}!


div.container.mx-auto
  - if @current_table == 'teacher_students'
    .mb-4
      h2.text-xl.font-bold.mb-4 Список учеников
      = turbo_frame_tag "filter"
        = render partial: "filter_students", locals: { current_table: @current_table }
        = render partial: 'components/teacher_students_table', locals: { students: @students }

    .mt-8
      - if @students.present?
        = paginate @students, params: { student_name: params[:student_name], student_email: params[:student_email], student_phone: params[:student_phone] }

  - elsif @current_table == 'student_grades'
    = form_with model: Grade.new, url: teacher_grades_path, method: :post, local: true, class: "mb-4" do |form|
      = hidden_field_tag :table, @current_table
      .flex.space-x-4
        div
          = form.label :student_id, "Ученик", class: "p-2"
          = form.collection_select :student_id, Student.all, :id, :name, prompt: "", class: "border border-gray-300 p-2 rounded"
        div
          = form.label :subject_id, "Предмет", class: "p-2"
          - if @subjects.present?
            = form.collection_select :subject_id, @subjects, :id, :name, prompt: "", class: "border border-gray-300 p-2 rounded"
        div
          = form.label :date, "Дата", class: "p-2"
          = form.date_field :date, class: "border border-gray-300 p-2 rounded"
        div
          = form.label :value, "Оценка", class: "p-2"
          = form.number_field :value, class: "border border-gray-300 p-2 rounded", in: 1..5
      .flex.items-end
        = render partial: 'components/form_button', locals: { form: form, name: 'Поставить оценку' }

    div.mb-8
      h2.text-xl.font-bold.mb-4 Отображение оценок и среднего балла по предмету для каждого ученика
      = form_with url: teacher_dashboard_path(table: @current_table), method: :get, local: true, class: "mb-4" do |form|
        = hidden_field_tag :table, @current_table
        .flex.space-x-4
          div
            = form.label :subject_id, "Предмет", class: "p-2"
            - if @subjects.present?
              = form.select :subject_id, options_for_select(Subject.all.map { |sub| [sub.name, sub.id] }), include_blank: true, class: "border border-gray-300 p-2 rounded"
        .flex.items-end
          = render partial: 'components/form_button', locals: { form: form, name: 'Показать оценки и средний балл' }

      - if @selected_subject
        - @students.each do |student|
          - grades = student.grades.where(subject_id: @selected_subject.id).order(:date)
          - average_grade = grades.present? ? grades.average(:value).to_f : nil

          div.mt-4
            h3.text-lg.font-semibold.mb-2 Оценки для #{student.name} по предмету #{@selected_subject.name}

            = render partial: 'components/student_grades_table', locals: { grades: grades}

            - if average_grade.present?
              p.mt-2 Средний балл: #{number_with_precision(average_grade, precision: 2)}
            - else
              p.mt-2 Средний балл: -

  .flex.justify-center.mb-2
    = link_to 'Студенты', teacher_dashboard_path(table: 'teacher_students'), class: 'mx-2 px-4 py-2 bg-indigo-600 text-white rounded'
    = link_to 'Оценки', teacher_dashboard_path(table: 'student_grades'), class: 'mx-2 px-4 py-2 bg-pink-500 text-white rounded'